# Assignment 1

## Objective of this assignment
The objective is to get acquainted with the Python language, with emphasis on its scientific and numerical extensions, how data can be imported from other data sources, linear algebra basics that is needed in this course, visualization using principal component analysis (PCA) and the concept of similarity. Upon completing this exercise it is expected that you:

- Understand how data can be represented as vectors and matrices in numerical Python (NumPy).
- Can apply and interpret principal component analysis (PCA) for data visualization.
- Understand the various measures of similarity such as Jaccard and Cosine similarity and apply similarity measures to query for similar observations.

## ** Important: ** When handing in your homework:
+ Hand in the notebook (and nothing else) named as follows: StudentName1_snumber_StudentName2_snumber.ipynb
+ Provide clear and complete answers to the questions below under a seperate header (not hidden some-where in your source code), and make sure to explain your answers / motivate your choices. Add Markdown cells where necessary.
+ Source code, output graphs, derivations, etc., should be included in the notebook.
+ Hand-in: upload to Blackboard.
+ Include name, student number, assignment (especially in filenames)!
+ When working in pairs only one of you should upload the assignment, and report the name of your partner in your filename.
+ For problems or questions: use the BB discussion board or email the student assistants.

## Advised Reading and Exercise Material
**The following on-line materials are recommended:**

- <http://docs.python.org/tutorial> - Introduction into Python environment, syntax and data structures. Recommended reading - sections 1, 2, 3, 4 and 5.
- <http://www.scipy.org/Tentative_NumPy_Tutorial> - Tutorial introducing the scientific computing in Python, array and matrix operations, indexing and slicing matrices.
- <http://www.scipy.org/NumPy_for_Matlab_Users> - Useful reference to scientific computing in Python if you have previous experience with MATLAB programming.
- <https://www.datacamp.com/courses/intro-to-python-for-data-science> - Simple introduction to Data Science using Python.
- <http://matplotlib.sourceforge.net> - Documentation and examples related to matplotlib module, which we shall use extensively through the course to visualize data and results.
- Pang-Ning Tan, Michael Steinbach, and Vipin Kumar, {\em Introduction to Data Mining}, sections 2.1-2.3 + (A) + B.1
- <http://http://www.youtube.com/course?list=ECEA1FEF17E1E5C0DA> - Series of video tutorials covering basics of Python programming.
- Pang-Ning Tan, Michael Steinbach, and Vipin Kumar, {\em Introduction to Data Mining}, sections 2.4 + 3.1-3.2 + C.1-C.2


## 1.1 Python and Linear Algebra basics

**For this course we advise to only use NumPy ndarrays ndarrays to represent vectors and matrices. The numpy.matrix data type, although intuitive, is less supported and uses operators for multiplication differently. This means that you can't perform matrix multiplications symbollically, but that you will have to use functions from the NumPy library!** 

**1.1.1** (0.3 points) Generate (and print) the following vectors using functions from the *NumPy* package in Python: 
*Note: You do not have to print column vectors as columns!*

\begin{equation}
     \textbf{x} = \begin{pmatrix} 
         6 \\
         7 \\
         8 \\
         9 \\
         10 \\
         11 \\
         12
       \end{pmatrix}
     \textbf{y} = \begin{pmatrix} 
         3 \\
         7 \\
         11 \\
         15 \\
         19 \\
         23 \\
         27
       \end{pmatrix}
     \textbf{w} = \begin{pmatrix} 
         1 \\
         1 \\
         0 \\
         0.5 \\
         1 \\
         1.5 \\
         2 \\
         0 \\
         0 
       \end{pmatrix}
     \textbf{s} = \begin{pmatrix}
         100 \\
         98.8 \\
         97.6 \\
         96.4 \\
         95.2
       \end{pmatrix} 
     \textbf{z} = \begin{pmatrix}
         0.7 \\
         1.0 \\
         1.3 \\
         1.6 \\
         1.9 \\
         2.2 \\
         2.5 \\
         2.8
       \end{pmatrix}
  \end{equation}



In [254]:
#Import NumPy
import numpy as np
#You'll have to manually import libraries in the future!

In [255]:
##Generate the vectors in  using Python and NumPy 

x = np.array([6,7,8,9,10,11,12])
print(x)
y = np.array([3,4,11,15,19,23,27])
print(y)
w = np.array([1,1,0,0.5,1,1.5,2,0,0])
print(w)
s = np.array([100,98.8,97.6,96.4,95.2])
print(s)
z = np.array([0.7,1.0,1.3,1.6,1.9,2.2,2.5,2.8])
print(z)

[ 6  7  8  9 10 11 12]
[ 3  4 11 15 19 23 27]
[ 1.   1.   0.   0.5  1.   1.5  2.   0.   0. ]
[ 100.    98.8   97.6   96.4   95.2]
[ 0.7  1.   1.3  1.6  1.9  2.2  2.5  2.8]


Then compute the following operations:
> a. (0.2 points) **v** = 3**x** + **y**

In [256]:
##Answer to question 1.1.1a
v = 3 * x + y
print(v)

[21 25 35 42 49 56 63]


> b. (0.2 points) Compute the dot product between **x** and **y** and name it **q**


In [257]:
##Answer to question 1.1.1b
q = np.dot(x,y)
print(q)

1036


> c. (0.2 points) **t** = pi(**s** + 4) (element wise multiplication)

In [258]:
##Answer to question 1.1.1c
t = np.pi*(s+4)
print(t)

[ 326.72563597  322.95572479  319.1858136   315.41590242  311.64599124]


> d. (0.2 points) **z** = **z** - 1

In [259]:
##Answer to question 1.1.1d
z = z-1
print(z)

[-0.3  0.   0.3  0.6  0.9  1.2  1.5  1.8]


> e. (0.2 points) replace some values of x, such that the last three values in the vector are 4

In [260]:
##Answer to question 1.1.1e

alternativeSolution = x 
x[x >= 10] = 4

#Or based on slicing

alternativeSolution[4:] = 4

print(x)
print(alternativeSolution)

[6 7 8 9 4 4 4]
[6 7 8 9 4 4 4]


> f. (0.2 points) **r** = 2**w** - 5

In [261]:
##Answer to question 1.1.1f
r = 2 * w - 5
print(r)

[-3. -3. -5. -4. -3. -2. -1. -5. -5.]


**1.1.2** (0.25 points) Generate these matrices:

\begin{equation}
     \textbf{M} = \begin{pmatrix} 
         1 & 2 & 3 \\
         6 & 8 & 4 \\
         6 & 7 & 5          
         \end{pmatrix}
     \textbf{N} = \begin{pmatrix} 
         4 & 6 \\
         7 & 2 \\
         5 & 1
         \end{pmatrix}
     \textbf{P} = \begin{pmatrix} 
         2 & 5 \\
         5 & 5 
         \end{pmatrix}   
\end{equation}

Afterwards try and compute the operations for subquestions *a* up to and including *e* and print the resulting matrix. If some operations yield errors, give the reason as to why that happens.

*A hint: NumPy has functions for matrix operations you can, and should, use!*

In [262]:
##Generate the matrices using Python and NumPy

M = np.matrix([[1,2,3],[6,8,4],[6,7,5]])
N = np.matrix([[4,6],[7,2],[5,1]])
P = np.matrix([[2,5],[5,5]])
print(M)
print(N)
print(P)

[[1 2 3]
 [6 8 4]
 [6 7 5]]
[[4 6]
 [7 2]
 [5 1]]
[[2 5]
 [5 5]]


> a. (0.2 points) **A** = **MN** + **N**

In [263]:
##Answer to question 1.1.2a
A = M * N + N
print(A)

[[ 37  19]
 [107  58]
 [103  56]]


> b. (0.2 points) **B** = **N**<sup>T</sup>**M**

In [264]:
##Answer to question 1.1.2b

##Answer to question 1.1.2b
B = np.matmul(np.transpose(N),M)
print(B)

[[76 99 65]
 [24 35 31]]


> c. (0.2 points) **C** = **P**<sup>-1</sup> + **P**

In [265]:
##Answer to question 1.1.2c
C = np.linalg.inv(P) + P
print(C)

[[ 1.66666667  5.33333333]
 [ 5.33333333  4.86666667]]


> d. (0.2 points) **D** = **AC**(**C** + **B**)

In [266]:
##Answer to question 1.1.2d
#will yield an error because C+B is an impossible action
D = np.matmul(A,np.matmul(C, C+B))

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

> e. (0.2 points) Compute the eigenvalues and eigenvectors of **M**, **N**, and **P** (and print them).

In [ ]:
#added a column of zeroes to counter dimensionality issues calculating the eigenvalues.
print("eigenvalues M: ")
print(np.linalg.eig(M))
print("eigenvalues N: ")
zeroesN = np.zeros((3,1),dtype=np.int64)
print(np.linalg.eigvals(np.append(N, zeroesN, axis=1)))
print("eigenvalues P: ")
print(np.linalg.eigvals(P))

## 1.2 Principal Component Analysis

**1.2.1** many experimenters have a habit of using Microsoft Excel as their tool to record measurements from experiments. Fortunately Python can read Excel files. Various methods exist, of which the use of the Python library Pandas is arguably one of the easiest for the purpose of Data Mining.

The data used in this exercise is based on data from a chemical sensor obtained from the NanoNose project[1]. The data contains 8 sensors, named by the letters A-H, measuring the concentration of Water, Ethanol, Acetone, Heptane and Pentanol injected into a small gas chamber. The data will be represented in matrix form such that each column contains the 8 sensor measurements (i.e., sensor A-H) of the various compounds injected into the gas chamber.
> a. (0.2 points) Inspect the nanonose.xls file in the Data folder and make sure you understand how the data is stored in Excel.

> *Load the data in python using the Pandas library (use the read_excel() function). Make sure you read some of the Pandas documentation! Especially slicing, indexing and dropping are useful commands*

> *make sure to inspect the data first! You should cut out some rows and columns! You can easily inspect the structure of the Pandas dataframe using the head() function.*

> *Finally use the as_matrix() function to cast the Pandas dataframe to a NumPy array. Note: counterintuitively, this yields an object of type: numpy.ndarray, not of type numpy.matrix!*

In [ ]:
import pandas as pd

data1 = pd.read_excel('Data/nanonose.xls')


#Removed 'empty' row, kept important headers
data2 = data1.iloc[1:]
#Removed empty column
data2 = data2.drop(data2.columns[2], axis=1)
#Inspect the data manually

print(data2.head())

#Creating dataset for SVD for future use
dataSVD = data2.iloc[:, 2:9]
#Inspect SVD Dataset
print(dataSVD.head())
#Casting the pandas dataframe to a NumPy matrix
dataAsNumpy = data2.as_matrix()

dataAsNumpy.shape


> b. (0.3 points) The data resides in what can be seen as an 8-dimensional space. Each dimension (column), corresponds to one of the 8 NanoNose sensors. Multidimensional (>3) data is hard to visualize, as we are unable to plot that many dimensions simultaneously.

> Using the matplotlib library, plot the attributes A and B against each other. After you have plotted A against B, also plot a few other combinations of attributes. Plot at least 4 different combinations. 

> *Do not forget to label your axes and add a figure description!*

> NOTE: If you want to plot inside the Jupyter notebook use the following command after you imported the library: 
*%matplotlib inline* 

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
#Seperating columns for easy plotting
A = data2['A']
B = data2['B']
C = data2['C']
D = data2['D']
E = data2['E']
F = data2['F']
G = data2['G']
H = data2['H']

#Plotting the seperate columns
plt.figure(0)
plt.scatter(A, B)
plt.xlabel('Sensor A \n Scatterplot sensor A~B', fontsize=14)
plt.ylabel('Sensor B', fontsize=14)

plt.figure(1)
plt.scatter(F, G)
plt.xlabel('Sensor F \n Scatterplot sensor F~G', fontsize=14)
plt.ylabel('Sensor G', fontsize=14)


plt.figure(2)
plt.scatter(D, E)
plt.xlabel('Sensor D \n Scatterplot sensor D~E', fontsize=14)
plt.ylabel('Sensor E', fontsize=14)


plt.figure(3)
plt.scatter(F, A)
plt.xlabel('Sensor F \n Scatterplot sensor F~A', fontsize=14)
plt.ylabel('Sensor A', fontsize=14)


plt.figure(4)
plt.scatter(C, H)
plt.xlabel('Sensor C \n Scatterplot sensor C~H', fontsize=14)
plt.ylabel('Sensor H', fontsize=14)



1.2.2 Principal Component Analysis, more commonly known as PCA, can be cleverly used to better visualize high dimensional data. 

> a. (1 point) Explain what PCA is and when it can be used. Make sure to provide an in-depth explanation and note what the drawbacks and limitations are.

*Double click to type your answer here*

To apply PCA we must first mean center the data. mean centering means that the mean value for an attribute is subtracted from that attribute. 

> b. (0.5 points) Why do we first need to mean center the data before applying PCA?

*Double click to type your answer here*

In practice, applying PCA comes down to a series of matrix operations, this is useful, as matrix operations can be applied with little effort and can be computed in relatively little time.

The given data **X**, must first be mean centered. This can be easily done by calculating a row vector **μ** containing the mean values of each attribute and then subtracting it from **X** (**Y** = **X** - **1μ**, where **1** is a column vector of size **N** x 1, with N indicating the number of observations in the original data).

Then, the Singular Value Decomposition, or SVD, of **Y**, the mean centered data, can be calculated. **Y** = **USV**<sup>T</sup>. In practice, this is often done using the numpy.linalg.svd() function.

Using SVD on **Y** yields a series of vectors which can be used to project the data onto specific Principal Components (PCs). The entire dataset can be projected onto the Principal Components by multiplying **Z** = **Y\*V**, where **Z** indicates the projected data. Alternatively, one could project onto just a subset of all the PCs by indexing in the multiplication. For example: **Z** = **Y\*V[:,1]** would yield the projection of the data onto the first PC.

> c. (1 point)  Apply PCA (using the aforementioned method) on the Nanonose data and visualize a scatterplot of the projection of the data onto the first two PCs.

In [ ]:
#Mean centering every column by substracting every element
#by the mean of the column
AMeanCentered = A -A.mean()
BMeanCentered = B -B.mean()
CMeanCentered = C -C.mean()
DMeanCentered = D -D.mean()
EMeanCentered = E -E.mean()
FMeanCentered = F -F.mean()
GMeanCentered = G -G.mean()
HMeanCentered = H -H.mean()





meanCenteredDf = pd.concat([AMeanCentered, BMeanCentered, CMeanCentered, DMeanCentered, 
            EMeanCentered, FMeanCentered, GMeanCentered, HMeanCentered], axis=1)
Y = meanCenteredDf.as_matrix()

U, S,V = np.linalg.svd(Y)



Z = np.matmul(Y,V[:,0:2])


plt.figure(5)
plt.scatter(Z[:,[0]],Z[:,[1]])
plt.xlabel('Principle component 1 \n PCA first 2 PCs', fontsize=14)
plt.ylabel('Principle component', fontsize=14)

> d. (1 point) Alternatively, one could use EigenValue Decomposition, EVD, instead of SVD. What are the similarities and differences between SVD and EVD? Can both be applied in each case?

*Double click to type your answer here*

PCA attempts to explain as much of the variance in data with as few PCs as possible. The variance explained by each of the PCs **m** can be calculated using the following formula: 
$\rho_m = 1 - \frac{\|{Y} - {u}_m s_{mm} {v}_m^T\|^2_F}{\|{Y}\|^2_F} = \frac{s_{mm}^2}{\displaystyle \sum_{m'=1}^M s^2_{m'm'}}$

Which indicates that the variation $\rho$ for a given **m** can be calculated by dividing the squared singular value of component **m** by the sum of all squared singular values. 
> e. (1 point) Calculate the row vector $\rho$ containing all values of $\rho$ for all PCs **m**. Create a bar plot with the variance explained on the Y axis and the number of the PC on the X axis. 

In [ ]:
sumS = sum(s)
m = (S**2)/  sumS
print(m)
n_groups = 8
index = np.arange(n_groups)
plt.figure(6)
plt.bar(index, m)
plt.xlabel('All 8 Principal components \n variance explained by PC' , fontsize=14)
plt.ylabel('Variance', fontsize=14)


> f. (0.5 points) How much of the variance is explained by the first three PCs?

In [ ]:
#the variance explained by the first three PCs is calculated by
# adding them up
varianceFirstThree = m[0] + m[1] + m[2]
print(varianceFirstThree)

*Double click to type your answer here*

The columns of **V** indicate the exact projection of the data onto the PCs. In a way, a PC is nothing other than a linear combination of the original attributes. 
> g. (0.5 points) Which attributes are primarily represented by the first PC? What would cause an observation to have a large negative/positive projection onto the second principal component?

In [ ]:
print(V)

*Double click to type your answer here*

## 1.3 Similarity measures

We will use a subset of the data on wild faces described by Berg in 2005 transformed to a total
of 1000 gray scale images of size 40x40 pixels, we will attempt to find faces in the
data base that are the most similar to a given query face. To measure similarity we
will consider the following measures: SMC, Jaccard, Cosine, ExtendedJaccard, and
Correlation. These measures of similarity are described in *Introduction to Data Mining*, page 73-77 and are given by

\begin{eqnarray*}
\textrm{SMC}({x},{y}) & = & \frac{\textrm{Number of matching attribute values}}{\textrm{Number of attributes}} \\
\textrm{Jaccard}({x},{y}) & = & \frac{\textrm{Number of matching presences}}{\textrm{Number of attributes not involved in 00 matches}} \\
\textrm{Cosine}({x},{y}) & = & \frac{{x}^T {y}}{\|{x}\| \|{y}\|} \\
\textrm{ExtendedJaccard}({x},{y}) & = & \frac{{x}^T {y}}{\|{x}\|^2 + \|{y}\|^2 - {x}^T {y}} \\
\textrm{Correlation}({x},{y}) & = & \frac{\textrm{cov}({x},{y})}{\textrm{std}({x}) \textrm{std}({y})}
\end{eqnarray*}
where $\textrm{cov}({x},{y})$ denotes the covariance between ${x}$ and ${y}$ and $\textrm{std}({x})$ denotes the standard deviation of ${x}$.

Notice that the SMC and Jaccard similarity measures only are defined for binary
data, i.e., data that takes values in $\{0,1\}$. As the data we analyze is non-binary,
we will transform the data to be binary when calculating these two measures of
similarity by setting
$x_i = \left\{ \begin{array}{ll} 0 & \textrm{if~} x_i < \textrm{median}({x}) \\
                                1 & \textrm{otherwise.} \end{array} \right.$
                                
### 1.3.1
> (0.5 points) Inspect and run the simfaces function from the Toolbox. The function loads the CBCL face database, computes the similarity between a selected query image and all others, and display the query image, the 5 most similar images, and the 5 least similar images. The value of the used similarity measure is shown below each image. Try changing the query image and the similarity measure and see what happens. Which similarity measures produce similar results? Which one gives the best result? Why?

> Give a quick overview of the settings (image number and similarity measure) for each time you run the script! Remember to leave all results open!



In [ ]:
from Toolbox.simfaces import simfaces

simfaces(587,'cosine')

Similar results; jaccard, smc (yield the same faces with slightly different similarity scores) best result; cosine seems to be yielding the best results when judging from a visual aspect.


> (0.75 points) We will investigate how scaling and translation impact the following three
similarity measures: Cosine, ExtendedJaccard, and Correlation. Let $\alpha$ and $\beta$ be two constants. Using Python, calculate the following similarity measures, and check if the statements below are correct.

\begin{eqnarray*}
\textrm{Cosine}(\alpha{x},{y}) & = & \textrm{Cosine}({x},{y}) \\
\textrm{ExtendedJaccard}(\alpha{x},{y}) & = & \textrm{ExtendedJaccard}({x},{y}) \\
\textrm{Correlation}(\alpha{x},{y}) & = & \textrm{Correlation}({x},{y}) \\
\textrm{Cosine}(\beta + {x},{y}) & = & \textrm{Cosine}({x},{y}) \\
\textrm{ExtendedJaccard}(\beta + {x},{y}) & = & \textrm{ExtendedJaccard}({x},{y}) \\
\textrm{Correlation}(\beta + {x},{y}) & = & \textrm{Correlation}({x},{y})
\end{eqnarray*}

> Type help similarity, or study similarity.py, to learn about the function that is used to compute the similarity measures. Do not forget to also import similarity.py!

> Even though a similarity measure is theoretically invariant e.g.\ to scaling, it might not be exactly invariant numerically.

> Do not forget to also provide an explanation in addition to the calculations!


In [267]:
from Toolbox.similarity import similarity
import numpy as np
matrixone = np.random.random((4,4))
matrixtwo = np.random.random((4,4))
matrixone = (matrixone*100).astype(int)
matrixtwo = (matrixtwo*100).astype(int)
#print(matrixone)
#print(matrixtwo)
#defining constants:
A = 20
B = 35

#Cosine calculations:
print("cosine with constant multiplication: 2 matrices are the same so statement is correct")
#vanilla:
print(similarity(matrixone,matrixtwo,'cos'))
#multiplied by constant:
print(similarity(matrixone*A,matrixtwo,'cos'))

#extendedjaccard:
print("extended jaccard with constant multiplication: 2 matrices are the same so statement is correct")
#vanilla:
print(similarity(matrixone,matrixtwo,'ext'))
#multiplied by constant:
print(similarity(matrixone*A,matrixtwo,'ext'))

#Correlation:
print("correlation with constant multiplication: 2 matrices are the same so statement is correct")
#vanilla:
print(similarity(matrixone,matrixtwo,'cor'))
#multiplied by constant:
print(similarity(matrixone*A,matrixtwo,'cor'))

#with constant addition:
#cosine calculations:
print("cosine with constant addition: 2 matrices are not the same so statement is incorrect")
#vanilla:
print(similarity(matrixone,matrixtwo,'cos'))
#with constant addition
print(similarity(matrixone+B,matrixtwo,'cos'))

#extended jaccard calculations:
print("extended jaccard with constant addition: 2 matrices are the same so statement is correct")
#vanilla:
print(similarity(matrixone,matrixtwo,'ext'))
#with constant addition
print(similarity(matrixone+B,matrixtwo,'ext'))

#correlation calculations:
print("correlation with constant addition: 2 matrices are the same so statement is correct")
#vanilla:
print(similarity(matrixone,matrixtwo,'cor'))
#with constant addition
print(similarity(matrixone+B,matrixtwo,'cor'))

cosine with constant multiplication: 2 matrices are the same so statement is correct
[[ 0.86770053  0.94499463  0.99463045  0.68461117]
 [ 0.81262809  0.93092623  0.99378637  0.5889941 ]
 [ 0.9553625   0.93661781  0.87392146  0.79483254]
 [ 0.93588892  0.94061523  0.79186077  0.60673901]]
[[ 0.86770053  0.94499463  0.99463045  0.68461117]
 [ 0.81262809  0.93092623  0.99378637  0.5889941 ]
 [ 0.9553625   0.93661781  0.87392146  0.79483254]
 [ 0.93588892  0.94061523  0.79186077  0.60673901]]
extended jaccard with constant multiplication: 2 matrices are the same so statement is correct
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
correlation with constant multiplication: 2 matrices are the same so statement is correct
[[ 0.30448583  0.49168072  0.98914949 -0.1445224 ]
 [ 0.13646793  0.53896883  0.96389778 -0.3328999 ]
 [ 0.9114815   0.38672261 -0.13599852  0.42139921]
 [ 0.76642656

/home/jdm/RU/DataMining/Assignment_1/Toolbox/similarity.py:44: RuntimeWarning: overflow encountered in exp
  sim = XYt / (np.log( np.exp(sum(np.power(X.T,2))).T * np.exp(sum(np.power(Y.T,2))) ) - XYt)


using randomly generated matrices of the same size, and the similarity calculations; the results can be compared to see whether they differ from each other. for the constant of a the number 20 was chosen, for constant b the number 35. all other calculations were performed using numpy and the given library. furthermore, the print statements show what kind of calculation was executed along with the method, the exact code was commented so you can tell which matrix in the printed output belongs to which calculation.

## Turning in the Jupyter Notebook
Do not forget to read the provided guidelines regarding the expectations and grading of your report. You can find these on Blackboard!

## References
[1] Tommy S Alstrøm, Jan Larsen, Claus H Nielsen, and Niels B Larsen. Data-driven
modeling of nano-nose gas sensor arrays. In SPIE Defense, Security, and Sensing,
pages 76970U76970U. International Society for Optics and Photonics, 2010. URL
http://www.nanonose.dk.